version: '2.3'
services:
  s6-overlay-alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
      args:
        PACKAGE: ${PACKAGE}
        VERSION: ${VERSION}
      labels:
        org.label-schema.name: "s6-overlay"
        org.label-schema.schema-version: "1.0"
        org.label-schema.vendor: "GlacialMagma"
        org.label-schema.vcs-url: "https://github.com/GlacialMagma/docker-s6-overlay"
        org.label-schema.description: "Docker base image with the s6-overlay init."
        org.label-schema.version: ${VERSION}
        org.label-schema.vcs-ref: ${VCS_REF}
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}-alpine